Repository readikus/royston, pull requests merged in 2021-10, with the labels that each got.

#25 tests: migrate tests to pytests
  pyproject.toml
  scripts.py
  tests/royston_doc2vec_test.py
  tests/royston_prune_test.py
  tests/royston_test.py
  tests/trend_cluster_test.py
Labels: hacktoberfest-accepted

#27 Fixed broken test date
  pyproject.toml
  royston/royston.py
  scripts.py
  tests/royston_doc2vec_test.py
  tests/royston_prune_test.py
  tests/royston_test.py
Labels: hacktoberfest

#30 Fixture
  pyproject.toml
  pytest.ini
  royston/royston.py
  royston/trend_cluster.py
  scripts.py
  tests/conftest.py
  tests/fixtures/__init__.py
  tests/fixtures/add.py
  tests/royston_doc2vec_test.py
  tests/royston_prune_test.py
  tests/royston_test.py
  tests/royston_trend_cluster_test.py
Labels: enhancement, hacktoberfest
